### ISSUE TITLE
Increment is too large for texture.

### ISSUE THREAD

**Issue by YKDZ** [Ehhthan/HappyHud-Issues#36]
https://mcpaste.com/5920b917912073db5e4002e9ebd62bf2
This error will appear when server open.
It will be fixed when degraded to Happyhud 0.2.9.

**Comment by Ehhthan** [comment]
This message means that your increment number is too big for the texture that you are using. If your orientation is horizontal that means your width is less than your increment or if you are using orientation vertical your height is less than your increment. The reason it works in older versions is because it will just auto set to the max increment if it detects it being too large. Conditions make it so this is not possible.

**Comment by Phoenix-99** [comment]
it happens the same to me, but when i've installed HappyHUD PremadePack [Vanilla & MMOCore] 1.1.1, i do /happyhud reload an console gives me Increment is too large for texture

**Comment by Ehhthan** [comment]
> it happens the same to me, but when i've installed HappyHUD PremadePack [Vanilla & MMOCore] 1.1.1, i do /happyhud reload an console gives me Increment is too large for texture

I've explained above how to fix it, the issue is that pack relied on an error correction feature instead of properly configuring. Let the author of that pack know so they can fix it.
